export {default as Tiny} from './Tiny'
export {default as MainLayout} from './MainLayout'
export {default as Divider} from './Divider'
export {default as Text} from './Text'
export {default as Heading} from './Heading'
export {default as SubHeading} from './SubHeading'
export {default as Button} from './Button'
export {default as FormInput} from './FormInput'