name: Inclusive Website Staging Deployment
on:
  push:
    branches:
      - cicd/staging
jobs:
  build-staging-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: cicd/staging
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm run build
      - run: npm run export