name: Inclusive Website Staging Deployment
on:
  push:
    branches:
      - cicd/staging
jobs:
  fetch-website-staging-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: cicd/staging
      - run: ls -hal